# Generated by Django 4.1.3 on 2022-12-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name1',
            new_name='name',
        ),
    ]
