# Generated by Django 4.1.3 on 2022-12-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_name1_people_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='name1',
        ),
    ]
